//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int idEmpl { get; set; }
        public string nomEmpl { get; set; }
        public string apeEmpl { get; set; }
        public int edadEmpl { get; set; }
    }
}
